config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users,
	controllers: {
		sessions: 'portal/sessions',
		:registrations => "portal/registrations",
		:passwords => "portal/passwords"
	},
	:path_names => { 
		:sign_in => 'login', 
		:sign_out => 'logout'
	}

  resources :colours
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :varieties
end

app/models/variety.rb
class Variety < ApplicationRecord
	has_many :products
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
	before_action :set_variety, only: [:show, :edit, :update, :destroy]

  def index
    @varieties = Variety.all
  end

  def show
  end

  def new
    @variety = Variety.new
  end

  def edit
  end

  def create
    @variety = Variety.new(variety_params)

    respond_to do |format|
      if @variety.save
        format.html { redirect_to @variety, notice: 'Variety was successfully created.' }        
      else
        format.html { render :new }        
      end
    end
  end

  def update
    respond_to do |format|
      if @variety.update(variety_params)
        format.html { redirect_to @variety, notice: 'Variety was successfully updated.' }        
      else
        format.html { render :edit }        
      end
    end
  end

  def destroy
    @variety.destroy
    respond_to do |format|
      format.html { redirect_to varieties_url, notice: 'Variety was successfully destroyed.' }      
    end
  end

  private
    def set_variety
      @variety = Variety.find(params[:id])
    end

    def variety_params
      params.require(:variety).permit(:name, :description, :note, :veriety_id)
    end
end

app/helpers/varieties_helper.rb
module VarietiesHelper
end

app/views/varieties/edit.html.erb
<%= @edit %>
<br>
kembali ke <%=link_to 'awal', varieties_path %>
<br>
<%= render "varieties/shared/form" %>

app/views/varieties/index.html.erb
1. <% @variabel %> -> ga muncul <br>
2. <%= @variabel %> -> muncul <br>
<br>
<%=link_to 'new', new_variety_path %>
<%=link_to 'edit', edit_variety_path(1) %>
<%=link_to 'show', variety_path(1) %>
<br>
<% @varieties.each do |variety| %>
<%= variety.name %>
<% end %>

app/views/varieties/new.html.erb
<%= @new %>
<br>
kembali ke <%=link_to 'awal', varieties_path %>
<br>
<%= render "varieties/shared/form" %>

app/views/varieties/show.html.erb
<%= @show %>
<br>
kembali ke <%=link_to 'awal', varieties_path %>
<br>
<%= @variety.name %>