config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users,
	controllers: {
		sessions: 'portal/sessions',
		:registrations => "portal/registrations",
		:passwords => "portal/passwords"
	},
	:path_names => { 
		:sign_in => 'login', 
		:sign_out => 'logout'
	}

  resources :colours
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :varieties
end

app/models/colour.rb
class Colour < ApplicationRecord	
	has_many :product_colour
	has_many :products through: :product_colour	

end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :set_colour, only: [:show, :edit, :update, :destroy]

  # GET /colours
  # GET /colours.json
  def index
    @colours = Colour.all
  end

  # GET /colours/1
  # GET /colours/1.json
  def show
  end

  # GET /colours/new
  def new
    @colour = Colour.new
  end

  # GET /colours/1/edit
  def edit
  end

  # POST /colours
  # POST /colours.json
  def create
    @colour = Colour.new(colour_params)

    respond_to do |format|
      if @colour.save
        format.html { redirect_to @colour, notice: 'Colour was successfully created.' }
        format.json { render :show, status: :created, location: @colour }
      else
        format.html { render :new }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colours/1
  # PATCH/PUT /colours/1.json
  def update
    respond_to do |format|
      if @colour.update(colour_params)
        format.html { redirect_to @colour, notice: 'Colour was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour }
      else
        format.html { render :edit }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colours/1
  # DELETE /colours/1.json
  def destroy
    @colour.destroy
    respond_to do |format|
      format.html { redirect_to colours_url, notice: 'Colour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_params
      params.require(:colour).permit(:name, :description)
    end
end

app/helpers/colours_helper.rb
module ColoursHelper
end

app/views/colours/_form.html.erb
<%= form_with(model: colour, local: true) do |form| %>
  <% if colour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colour.errors.count, "error") %> prohibited this colour from being saved:</h2>

      <ul>
      <% colour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colours/edit.html.erb
<h1>Editing Colour</h1>

<%= render 'form', colour: @colour %>

<%= link_to 'Show', @colour %> |
<%= link_to 'Back', colours_path %>

app/views/colours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colours.each do |colour| %>
      <tr>
        <td><%= colour.name %></td>
        <td><%= colour.description %></td>
        <td><%= link_to 'Show', colour %></td>
        <td><%= link_to 'Edit', edit_colour_path(colour) %></td>
        <td><%= link_to 'Destroy', colour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colour', new_colour_path %>

app/views/colours/new.html.erb
<h1>New Colour</h1>

<%= render 'form', colour: @colour %>

<%= link_to 'Back', colours_path %>

app/views/colours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colour.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @colour.description %>
</p>

<%= link_to 'Edit', edit_colour_path(@colour) %> |
<%= link_to 'Back', colours_path %>