config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users,
	controllers: {
		sessions: 'portal/sessions',
		:registrations => "portal/registrations",
		:passwords => "portal/passwords"
	},
	:path_names => { 
		:sign_in => 'login', 
		:sign_out => 'logout'
	}

  resources :colours
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :varieties
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :variety

	has_many :product_colour
	#has_many :colours through: :product_colour
	
	validates :name , :presence => true

	#default_scope where('name=test')

	#scope :name where(name='test')
end

app/controllers/products_controller.rb
class ProductsController < BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
      	ProductMailer.send_email_when_product(@product).deliver
        format.html { redirect_to @product, notice: 'Product was successfully created.' }               
      else
        format.html { render :new }        
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }        
      else
        format.html { render :edit }        
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }      
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :variety_id, :stock, :price, :colour_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= @edit %>
<br>
kembali ke <%=link_to 'awal', products_path %>
<br>
<%= render "products/shared/form" %>

app/views/products/index.html.erb
1. <% @variabel %> -> ga muncul <br>
2. <%= @variabel %> -> muncul <br>
<br>
<%=link_to 'new', new_product_path %>
<%=link_to 'edit', edit_product_path(1) %>
<%=link_to 'show', product_path(1) %>
<%=link_to 'keluar', destroy_user_session_path , method: :delete %> 

<br>
<% @products.each do |product| %>
<%= product.name %>
<% end %>

app/views/products/new.html.erb
<%= @new %>
<br>
kembali ke <%=link_to 'awal', products_path %>
<br>
<%= render "products/shared/form" %>

app/views/products/show.html.erb
<%= @show %>
<%= notice %>
<br>
kembali ke <%=link_to 'awal', products_path %>
<br>
<%= @product.name %>
<%= @product.variety.name %>